"""Constants for UniFi Network Rules services."""

# Service names
SERVICE_REFRESH = "refresh"
SERVICE_BACKUP = "backup_rules"
SERVICE_RESTORE = "restore_rules"
SERVICE_BULK_UPDATE = "bulk_update_rules"
SERVICE_DELETE_RULE = "delete_rule"
SERVICE_APPLY_TEMPLATE = "apply_template"
SERVICE_SAVE_TEMPLATE = "save_template"
SERVICE_FORCE_CLEANUP = "force_cleanup"
SERVICE_FORCE_REMOVE_STALE = "force_remove_stale"
SERVICE_TOGGLE_RULE = "toggle_rule"
SERVICE_REFRESH_DATA = "refresh_data"
SERVICE_SYNC_REMOTE_CURATED = "sync_remote_curated"

# Schema fields
CONF_FILENAME = "filename"
CONF_RULE_IDS = "rule_ids"
CONF_NAME_FILTER = "name_filter"
CONF_RULE_TYPES = "rule_types"
CONF_TEMPLATE_ID = "template_id"
CONF_TEMPLATE = "template"
CONF_VARIABLES = "variables"
CONF_STATE = "state"
CONF_RULE_ID = "rule_id"
CONF_RULE_TYPE = "rule_type"
CONF_OBJECT_SETS = "object_sets"
CONF_GITHUB_CLONE_URL = "github_clone_url"
CONF_GITHUB_REF = "ref"
CONF_REMOTE_FILE = "file"
CONF_REMOTE_FILES = "files"
CONF_REMOTE_URLS = "urls"

# Signal for entity cleanup
SIGNAL_ENTITIES_CLEANUP = "unifi_network_rules_cleanup"
