name: Home Assistant Validation

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  checks: write
  pull-requests: write
  statuses: write

jobs:
  validate:
    name: Validate with hassfest
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "home-assistant/actions/hassfest@master"
      - name: Report Hassfest Status
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const conclusion = '${{ job.status }}'.toLowerCase();
            await github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: conclusion === 'success' ? 'success' : 'failure',
              description: conclusion === 'success' ? 'Hassfest validation passed!' : 'Hassfest validation failed.',
              context: 'Hassfest Validation'
            });
